CREATE DATABASE mybank;

CREATE TABLE IF NOT EXISTS PESSOAS (
  ID VARCHAR NOT NULL UNIQUE,
  NOME VARCHAR NULL,
  CONTRATO_ID VARCHAR NOT NULL,
  INADIMPLENTE VARCHAR NULL,
  DT_COMPLETO DATE,
  FOREIGN KEY(CONTRATO_ID) REFERENCES CONTRATOS(ID)
);

CREATE TABLE IF NOT EXISTS CONTRATOS (
  ID VARCHAR NOT NULL UNIQUE,
  VALOR_PARCELA VARCHAR NOT NULL,
  PARCELAS VARCHAR NOT NULL 
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
  ID VARCHAR NOT NULL,
  PESSOA_ID VARCHAR NOT NULL,
  DT_PAGAMENTO DATE,
  FOREIGN KEY(PESSOA_ID) REFERENCES PESSOAS(ID)
);
