version: "3"
services:
    postgres:
        container_name: pgs2
        image: "postgres:alpine"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - ./.dbdata:/var/lib/postgresql/data
